//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidat
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prnom { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string lieu_naissance { get; set; }
        public string adresse { get; set; }
        public string nationalite { get; set; }
        public string ville { get; set; }
        public string tel { get; set; }
        public string fix { get; set; }
        public string cin { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string cne { get; set; }
        public string type_bac { get; set; }
        public string annee_bac { get; set; }
        public string mention_bac { get; set; }
        public string diplome { get; set; }
        public string ecole { get; set; }
        public string ville_ecole { get; set; }
        public Nullable<bool> redouble_1ere_annee { get; set; }
        public Nullable<bool> redouble_2eme_annee { get; set; }
        public Nullable<bool> redouble_3eme_annee { get; set; }
        public Nullable<double> note_S1 { get; set; }
        public Nullable<double> note_S2 { get; set; }
        public Nullable<double> note_S3 { get; set; }
        public Nullable<double> note_S4 { get; set; }
        public Nullable<double> note_S5 { get; set; }
        public Nullable<double> note_S6 { get; set; }
        public byte[] photo_identite { get; set; }
        public byte[] scan_bac { get; set; }
        public byte[] scan_diplome { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<double> note_concour { get; set; }
        public string filiere_choisie { get; set; }
    }
}
